server.port=${PORT:8080}
app.jwt.secret=${JWT_SECRET}
users.service.url=${USERS_SERVICE_URL}
karma.service.url=${KARMA_SERVICE_URL}
notification.service.url=${NOTIFICATION_SERVICE_URL}
logging.level.org.springframework.security=WARN
